from pathlib import Path

import pytest

from bonsai.errors import BonsaiCommandError
from bonsai.git import (
    parse_default_branch,
    remote_branch_exists,
)
from bonsai.models import (
    CommandResult,
    CommandSpec,
    FileCopy,
    FileWrite,
    ManagedWorktree,
)
from bonsai.ports import allocate_slot
from bonsai.process import RecordingRunner
from bonsai.workflows import (
    app_snippets_dir,
    apply_file_copies,
    global_caddy_paths,
    write_files,
)


def test_allocate_slot_uses_lowest_available_positive_integer() -> None:
    worktrees = {
        "a": ManagedWorktree(path="a", slug="a", slot=1),
        "c": ManagedWorktree(path="c", slug="c", slot=3),
    }

    assert allocate_slot(worktrees) == 2


def test_allocate_slot_returns_one_for_empty_state() -> None:
    assert allocate_slot({}) == 1


def test_parse_default_branch_from_ls_remote_symref() -> None:
    output = "ref: refs/heads/staging\tHEAD\nabc123\tHEAD\n"

    assert parse_default_branch(output) == "staging"


def test_remote_branch_exists_uses_checked_runner_behavior() -> None:
    class FailingRunner:
        def run(
            self,
            argv: list[str],
            cwd: Path | None = None,
            check: bool = True,
        ) -> CommandResult:
            if check:
                raise BonsaiCommandError("network failure")
            return CommandResult(returncode=1)

    with pytest.raises(BonsaiCommandError, match="network failure"):
        remote_branch_exists(FailingRunner(), Path("/tmp/repo"), "feature")


def test_recording_runner_captures_commands_without_running_them() -> None:
    runner = RecordingRunner()

    result = runner.run(["git", "status"], cwd=Path("/tmp/repo"))

    assert result.returncode == 0
    assert runner.commands == [CommandSpec(argv=("git", "status"), cwd=Path("/tmp/repo"))]


def test_recording_runner_captures_stream_commands() -> None:
    runner = RecordingRunner()

    result = runner.run_stream(
        ["yarn", "dev"],
        cwd=Path("/tmp/worktree"),
        env={"FRONTEND_PORT": "4201"},
    )

    assert result == 0
    assert runner.commands == [
        CommandSpec(
            argv=("yarn", "dev"),
            cwd=Path("/tmp/worktree"),
            env=(("FRONTEND_PORT", "4201"),),
        )
    ]


def test_global_caddy_paths_resolve_under_home(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    root, snippets = global_caddy_paths()
    assert root == tmp_path / ".bonsai" / "Caddyfile"
    assert snippets == tmp_path / ".bonsai" / "caddy.d"


def test_app_snippets_dir_is_namespaced_by_app(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    assert app_snippets_dir("authentic") == tmp_path / ".bonsai" / "caddy.d" / "authentic"


def test_parse_env_content_ignores_comments_and_blank_lines() -> None:
    from bonsai.env import parse_env_content

    content = """
# Generated by bonsai. Do not edit by hand.
SLOT=1

COMPOSE_PROJECT_NAME=authentic-feature
VALUE_WITH_EQUALS=a=b
"""

    assert parse_env_content(content) == {
        "SLOT": "1",
        "COMPOSE_PROJECT_NAME": "authentic-feature",
        "VALUE_WITH_EQUALS": "a=b",
    }


def test_write_files_creates_parent_directories(tmp_path: Path) -> None:
    write_files((FileWrite(path=tmp_path / "a" / "b.txt", content="hello\n"),))

    assert (tmp_path / "a" / "b.txt").read_text(encoding="utf-8") == "hello\n"


def test_apply_file_copies_seeds_missing_target_without_overwriting(tmp_path: Path) -> None:
    source = tmp_path / "main" / ".env"
    target = tmp_path / "feature" / ".env"
    source.parent.mkdir()
    target.parent.mkdir()
    source.write_text("SECRET=shared\n", encoding="utf-8")
    target.write_text("SECRET=local\n", encoding="utf-8")

    apply_file_copies((FileCopy(source=source, target=target),))

    assert target.read_text(encoding="utf-8") == "SECRET=local\n"

    target.unlink()
    apply_file_copies((FileCopy(source=source, target=target),))

    assert target.read_text(encoding="utf-8") == "SECRET=shared\n"
