from __future__ import annotations

from pathlib import Path

from bonsai.caddy import (
    BOOT_BLOCK_BEGIN,
    BOOT_BLOCK_END,
    caddy_boot_config_path,
    merge_boot_config,
)
from bonsai.models import CommandResult
from bonsai.process import RecordingRunner

IMPORTS = [
    "import /Users/x/.bonsai/caddy.d/alpha/*.caddy",
    "import /Users/x/.bonsai/caddy.d/beta/*.caddy",
]


def test_merge_boot_config_owns_empty_file() -> None:
    result = merge_boot_config("", IMPORTS)
    assert result.startswith("# Generated by bonsai. Do not edit by hand.")
    assert "{\n\tlocal_certs\n}" in result
    assert BOOT_BLOCK_BEGIN in result
    assert "import /Users/x/.bonsai/caddy.d/alpha/*.caddy" in result
    assert "import /Users/x/.bonsai/caddy.d/beta/*.caddy" in result
    assert BOOT_BLOCK_END in result


def test_merge_boot_config_is_idempotent() -> None:
    once = merge_boot_config("", IMPORTS)
    assert merge_boot_config(once, IMPORTS) == once


def test_merge_boot_config_appends_to_foreign_content_untouched() -> None:
    existing = "example.com {\n\treverse_proxy localhost:9000\n}\n"
    result = merge_boot_config(existing, IMPORTS)
    assert result.startswith(existing)
    assert BOOT_BLOCK_BEGIN in result
    assert "import /Users/x/.bonsai/caddy.d/alpha/*.caddy" in result
    assert "local_certs" not in result


def test_merge_boot_config_refreshes_block_in_place() -> None:
    existing = (
        "example.com {\n}\n\n"
        f"{BOOT_BLOCK_BEGIN}\nimport /old/glob/*.caddy\n{BOOT_BLOCK_END}\n"
    )
    result = merge_boot_config(existing, IMPORTS)
    assert "/old/glob/*.caddy" not in result
    assert "import /Users/x/.bonsai/caddy.d/alpha/*.caddy" in result
    assert result.startswith("example.com {\n}\n")
    assert result.count(BOOT_BLOCK_BEGIN) == 1


def test_caddy_boot_config_path_uses_brew_prefix() -> None:
    class BrewRunner(RecordingRunner):
        def run(self, argv, cwd=None, check=True, env=None):
            if argv[:2] == ["brew", "--prefix"]:
                return CommandResult(returncode=0, stdout="/opt/homebrew\n")
            return CommandResult(returncode=0)

    path = caddy_boot_config_path(BrewRunner())
    assert path == Path("/opt/homebrew/etc/Caddyfile")


def test_caddy_boot_config_path_none_when_brew_fails() -> None:
    class NoBrewRunner(RecordingRunner):
        def run(self, argv, cwd=None, check=True, env=None):
            return CommandResult(returncode=1)

    assert caddy_boot_config_path(NoBrewRunner()) is None


def test_caddy_boot_config_path_none_when_brew_silent() -> None:
    # Plain RecordingRunner returns returncode 0 with empty stdout. This must
    # resolve to None so tests never write into a real Homebrew tree.
    assert caddy_boot_config_path(RecordingRunner()) is None
