from __future__ import annotations

from pathlib import Path

from bonsai.models import BonsaiConfig
from bonsai.slug import branch_slug
from bonsai.templates import render_template

GENERATED_FILE_HEADER = "# Generated by bonsai. Do not edit by hand."
STANDARD_BONSAI_ENV_KEYS = (
    "BONSAI_WORKSPACE_NAME",
    "BONSAI_BRANCH",
    "BONSAI_SLUG",
    "BONSAI_SLOT",
    "BONSAI_WORKTREE_PATH",
    "BONSAI_ROOT_PATH",
    "BONSAI_DEFAULT_BRANCH",
    "BONSAI_PRIMARY_URL",
)
RESERVED_USER_ENV_NAMES = frozenset(STANDARD_BONSAI_ENV_KEYS)
RESERVED_SERVICE_PORT_ENV_NAMES = frozenset({"SLOT", *STANDARD_BONSAI_ENV_KEYS})
RESERVED_TEMPLATE_KEYS = frozenset(
    {
        "name",
        "branch",
        "slug",
        "slot",
        "WORKTREE_PATH",
        "SLOT",
        *STANDARD_BONSAI_ENV_KEYS,
    }
)


def service_ports(config: BonsaiConfig, slot: int) -> dict[str, int]:
    for service in config.services:
        if service.port_env in RESERVED_TEMPLATE_KEYS:
            raise ValueError(f"Service port_env uses reserved environment name: {service.port_env}")
    return {service.port_env: service.base_port + slot for service in config.services}


def _workspace_root(worktree_path: Path, workspace_root: Path | None) -> Path:
    return workspace_root if workspace_root is not None else worktree_path.parent


def _default_branch(branch: str, config: BonsaiConfig, default_branch: str | None) -> str:
    return default_branch or config.base_branch or branch


def _primary_url(config: BonsaiConfig, values: dict[str, object]) -> str:
    try:
        service = config.primary_service()
    except ValueError:
        return ""
    if service.url is None:
        return ""
    try:
        return render_template(service.url, values)
    except (KeyError, ValueError):
        return ""


def standard_bonsai_env(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
    *,
    workspace_root: Path | None = None,
    default_branch: str | None = None,
) -> dict[str, str]:
    root_path = _workspace_root(worktree_path, workspace_root)
    slug = branch_slug(branch)
    values: dict[str, object] = {
        "name": config.name,
        "branch": branch,
        "slug": slug,
        "slot": slot,
        "WORKTREE_PATH": str(worktree_path),
    }
    values.update(service_ports(config, slot))
    env = {
        "BONSAI_WORKSPACE_NAME": config.name,
        "BONSAI_BRANCH": branch,
        "BONSAI_SLUG": slug,
        "BONSAI_SLOT": str(slot),
        "BONSAI_WORKTREE_PATH": str(worktree_path),
        "BONSAI_ROOT_PATH": str(root_path),
        "BONSAI_DEFAULT_BRANCH": _default_branch(branch, config, default_branch),
    }
    values.update(env)
    env["BONSAI_PRIMARY_URL"] = _primary_url(config, values)
    return env


def template_values(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
    *,
    workspace_root: Path | None = None,
    default_branch: str | None = None,
) -> dict[str, object]:
    values: dict[str, object] = {
        "name": config.name,
        "branch": branch,
        "slug": branch_slug(branch),
        "slot": slot,
        "WORKTREE_PATH": str(worktree_path),
    }
    values.update(service_ports(config, slot))
    values.update(
        standard_bonsai_env(
            config,
            branch,
            slot,
            worktree_path,
            workspace_root=workspace_root,
            default_branch=default_branch,
        )
    )
    return values


def render_env_local(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
    *,
    workspace_root: Path | None = None,
    default_branch: str | None = None,
) -> str:
    values = template_values(
        config,
        branch,
        slot,
        worktree_path,
        workspace_root=workspace_root,
        default_branch=default_branch,
    )
    lines = [
        GENERATED_FILE_HEADER,
        f"SLOT={slot}",
    ]

    for key, port in service_ports(config, slot).items():
        lines.append(f"{key}={port}")

    for key in STANDARD_BONSAI_ENV_KEYS:
        lines.append(f"{key}={values[key]}")

    lines.append("")
    for env in config.env:
        if env.name in RESERVED_USER_ENV_NAMES:
            raise ValueError(f"Config env uses reserved environment name: {env.name}")
        lines.append(f"{env.name}={render_template(env.value, values)}")

    return "\n".join(lines).rstrip() + "\n"


def render_root_caddyfile(app_snippet_dirs: list[Path]) -> str:
    lines = ["{", "\tlocal_certs", "}", ""]
    lines.extend(f"import {directory}/*.caddy" for directory in app_snippet_dirs)
    lines.append("")
    return "\n".join(lines)


def render_caddy_snippets(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
    *,
    workspace_root: Path | None = None,
    default_branch: str | None = None,
) -> dict[str, str]:
    values = template_values(
        config,
        branch,
        slot,
        worktree_path,
        workspace_root=workspace_root,
        default_branch=default_branch,
    )
    snippets: dict[str, str] = {}
    for service in config.public_services():
        if service.url is None:
            continue
        url = render_template(service.url, values)
        port = values[service.port_env]
        snippets[service.name] = "\n".join(
            [
                GENERATED_FILE_HEADER,
                f"{url} {{",
                "\ttls internal",
                f"\treverse_proxy localhost:{port}",
                "}",
                "",
            ]
        )
    return snippets
