from __future__ import annotations

from pathlib import Path

from bonsai.models import BonsaiConfig
from bonsai.slug import branch_slug
from bonsai.templates import render_template

GENERATED_FILE_HEADER = "# Generated by bonsai. Do not edit by hand."
RESERVED_TEMPLATE_KEYS = frozenset({"name", "branch", "slug", "slot", "WORKTREE_PATH"})


def service_ports(config: BonsaiConfig, slot: int) -> dict[str, int]:
    for service in config.services:
        if service.port_env in RESERVED_TEMPLATE_KEYS:
            raise ValueError(f"Service port_env uses reserved template key: {service.port_env}")
    return {service.port_env: service.base_port + slot for service in config.services}


def template_values(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
) -> dict[str, object]:
    values: dict[str, object] = {
        "name": config.name,
        "branch": branch,
        "slug": branch_slug(branch),
        "slot": slot,
        "WORKTREE_PATH": str(worktree_path),
    }
    values.update(service_ports(config, slot))
    return values


def render_env_local(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
) -> str:
    values = template_values(config, branch, slot, worktree_path)
    lines = [
        GENERATED_FILE_HEADER,
        f"SLOT={slot}",
    ]

    for key, port in service_ports(config, slot).items():
        lines.append(f"{key}={port}")

    lines.append("")
    for env in config.env:
        lines.append(f"{env.name}={render_template(env.value, values)}")

    return "\n".join(lines).rstrip() + "\n"


def render_root_caddyfile(app_snippet_dirs: list[Path]) -> str:
    lines = ["{", "\tlocal_certs", "}", ""]
    lines.extend(f"import {directory}/*.caddy" for directory in app_snippet_dirs)
    lines.append("")
    return "\n".join(lines)


def render_caddy_snippets(
    config: BonsaiConfig,
    branch: str,
    slot: int,
    worktree_path: Path,
) -> dict[str, str]:
    values = template_values(config, branch, slot, worktree_path)
    snippets: dict[str, str] = {}
    for service in config.public_services():
        if service.url is None:
            continue
        url = render_template(service.url, values)
        port = values[service.port_env]
        snippets[service.name] = "\n".join(
            [
                GENERATED_FILE_HEADER,
                f"{url} {{",
                "\ttls internal",
                f"\treverse_proxy localhost:{port}",
                "}",
                "",
            ]
        )
    return snippets
